names:
    ncbi_name : 'NM_006015'
    # ncbi_name : 'NM_006015.6'
    cluster_name : '17HG'
    output_name : 'ARID1A_polycistron'

files:
    mirna_polycistrons_file : 'data/mirna_polycistrons.fa'
    mirna_in_polycistron_file : 'data/mirna_in_polycistrons.csv'
    sirna_file : 'data/sirna_ARID1A_results_filter.xlsx'
    rna_fold_file : 'data/RNAfold_data.fa'
    rna_fold_out_file : 'data/RNAfold_output.out'
    rna_cofold_file : 'data/data_for_RNAcofold.fasta'
    rna_cofold_out_file : 'data/RNAcofoldresults.txt'


mirna_members : ['hsa-mir-17',
                 'hsa-mir-18a',
                 'hsa-mir-19a',
                 'hsa-mir-20a',
                 'hsa-mir-19b-1']

modes:
    pairs: 'random'